create table migrations
(
    id        int generated by default as identity primary key,
    version   text not null,
    applied_at timestamptz not null default now()
);

create table clients
(
    id                         int generated by default as identity primary key,
    name                       text        not null,
    billing_start_day_of_month int         not null,
    is_active                  boolean     not null,
    created_at                 timestamptz not null default now(),
    updated_at                 timestamptz not null default now()
);

create index on clients (id) where is_active;

create table client_documents
(
    id           int generated by default as identity primary key,
    client_id    int         not null references clients (id),
    name         text        not null,
    content_type text        not null,
    content      text        not null,
    summary      text        not null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create table client_summaries
(
    id         int generated by default as identity primary key,
    client_id  int         not null references clients (id),
    content    text        not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table work_items
(
    id             int generated by default as identity primary key,
    name           text        not null,
    work_item_type text        not null,
    status         text        not null,
    description    text        null,
    client_id      int         not null references clients (id),
    parent_id      int         null references work_items (id),
    custom_fields  jsonb       null,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create index on work_items (client_id) where parent_id is null;

create table work_item_documents
(
    id           int generated by default as identity primary key,
    work_item_id int         not null references work_items (id),
    name         text        not null,
    content_type text        not null,
    content      text        not null,
    summary      text        not null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);


create table work_item_changes
(
    id                 int generated by default as identity primary key,
    work_item_id       int         not null references work_items (id),
    summary_of_changes text        not null,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);


create table time_entries
(
    id           int generated by default as identity primary key,
    work_item_id int         not null references work_items (id),
    start_time   timestamptz not null,
    end_time     timestamptz null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create index on time_entries (work_item_id) where end_time is null;

insert into migrations (version) values ('000001-000160-initial');